server.port=8081
spring.application.name=firstpro

spring.datasource.url=jdbc:h2:mem:firstproject

spring.datasource.driverClassName=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true